### ISSUE TITLE
For RTL language (e.g. Hebrew and Arabic), the cursor goes to the opposite direction

### ISSUE THREAD

**Issue by justanotheranonymoususer** [Nordskog/SwiftKeyExi#11]
You swipe left, it moves right

**Comment by Nordskog** [comment]
Yup, the reason for this is that RTL languages are, predictably, laid-out in right-to-left, but still index normally.

The simple solution would be to always have the cursor move in the reverse when using a keyboard language that is RTL. 

The more proper solution would be to constantly check the surrounding text when scrolling, and do some index magic should we encounter RTL characters. You'll note that using the keyboard keys to move the cursor will result also result in it moving in the wrong direction.

It's basically a bit of a headache that I know I should deal with, but when we mix LTR and RTL text it becomes quite a headache.

**Comment by justanotheranonymoususer** [comment]
> The simple solution would be to always have the cursor move in the reverse when using a keyboard language that is RTL.

I think that will be enough. The second solution is not stable, you can end up swiping right and never arriving to the beginning of the text, since once you land on the RTL text it goes to the opposite direction.

**Comment by Nordskog** [comment]
Support for RTL text added in commit https://github.com/Nordskog/SwiftKeyExi/commit/7c612a2cee695ad15bae80cbc5f7d9204e1305ea

Will be included in next release.
