### ISSUE TITLE
Feature: Transparent keyboard

### ISSUE THREAD

**Issue by Nordskog** [Nordskog/SwiftKeyExi#16]
Make the keyboard transparent.

Making it transparent is simple, keeping it from pushing the layout up and just having empty space under the transparent bit less so.

**Comment by earboxer** [comment]
This would be most helpful when the keyboard is in floating mode. (and, by your description, easier to implement).

**Comment by Nordskog** [comment]
Added with commit https://github.com/Nordskog/SwiftKeyExi/commit/35ac1735b43b8d1a8c40db288a240ac210d84485
Will make the keyboard transparent even when not floating, which is fairly useless since there's nothing behind it. Will be included in 1.4.0.
