### ISSUE TITLE
Bug: Popups do not respect case

### ISSUE THREAD

**Issue by Nordskog** [Nordskog/SwiftKeyExi#18]
Popups are currently inserted verbatim as you enter them, ignoring whatever case the keyboard happens to be in. Case should match keyboard case. Words might be difficult.

**Comment by earboxer** [comment]
Is this a bug or a feature? For example, I rarely mean to use uppercase Π (π).

At the very least, it's inconsistent with the behavior of shortcuts.

**Comment by Nordskog** [comment]
I... had not thought of that.
Before I released v1.0, I included the option to manually set the upper case character, with it defaulting to the upper-case of whatever was input in the lower-case field.
The back-end still has the field, and it's just hidden in the interface, so resurrecting it would probably be the simplest solution.
The best solution though ... ? Also yes?

**Comment by Nordskog** [comment]
Fixed in commit https://github.com/Nordskog/SwiftKeyExi/commit/a2252a0aec8dbf3f8ec4ed084f27070965308573
Upper case defaults to ... upper case (locale ignored), but can also be manually set to anything.
