### ISSUE TITLE
[feature] Integrate "Disable Fullscreen Keyboard" by Shubhang Rathore

### ISSUE THREAD

**Issue by danielmmmm** [Nordskog/SwiftKeyExi#31]
Would it be possible to integrate "Disable Fullscreen Keyboard" by Shubhang Rathore into SwiftKeyExi?
https://github.com/xenon92/xposed-disable-fullscreen-keyboard

This module is incredibly helpful. It makes landscape typing better, because one can see e.g. the message one wants to reply to.
In addition, the switch from portrait to landscape (full screen keyboard) seems to be bugged. I had text disappearing, that I already typed in portrait mode, many times. Disabling fullscreen keyboard also circumvents this bug.

**Comment by Nordskog** [comment]
Added in commit https://github.com/Nordskog/SwiftKeyExi/commit/eba9f3d3390d72d3756eacbac0e2456a4e9809e4

The first textbox that is targeted after the setting is changed seems to stick with the old setting, but anything after that will respect the setting.

Will be in included in next release. Will be another day or two so the translators can catch up.

**Comment by danielmmmm** [comment]
Awesome, thanks a lot! :-)
