### ISSUE TITLE
not working on the latest update 

### ISSUE THREAD

**Issue by achozex** [Nordskog/SwiftKeyExi#42]
07-14 20:30:39.917 I/Xposed ( 5444): Exi/LoadPackageHook, Module loaded in com.touchtype.swiftkey
07-14 20:30:41.095 I/Xposed ( 5444): Removed hooks: overlayHooks base, Requirement not met
07-14 20:30:42.583 I/Xposed ( 5444): Removed hooks: KeyboardHooks base, Failed to Hook
07-14 20:30:42.585 E/Xposed ( 5444): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
07-14 20:30:42.585 E/Xposed ( 5444): at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:206)
07-14 20:30:42.585 E/Xposed ( 5444): at com.mayulive.swiftkeyexi.xposed.keyboard.KeyboardHooks.hookViewCreatedFallback(KeyboardHooks.java:54)
07-14 20:30:42.585 E/Xposed ( 5444): at com.mayulive.swiftkeyexi.xposed.keyboard.KeyboardHooks.HookAll(KeyboardHooks.java:392)
07-14 20:30:42.585 E/Xposed ( 5444): at com.mayulive.swiftkeyexi.xposed.Hooks.hookAll(Hooks.java:112)
07-14 20:30:42.585 E/Xposed ( 5444): at com.mayulive.swiftkeyexi.LoadPackageHook.handleLoadPackage(LoadPackageHook.java:52)
07-14 20:30:42.585 E/Xposed ( 5444): at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
07-14 20:30:42.585 E/Xposed ( 5444): at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
07-14 20:30:42.585 E/Xposed ( 5444): at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
07-14 20:30:42.585 E/Xposed ( 5444): at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
07-14 20:30:42.585 E/Xposed ( 5444): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
07-14 20:30:42.585 E/Xposed ( 5444): at android.app.ActivityThread.handleBindApplication(<Xposed>)
07-14 20:30:42.585 E/Xposed ( 5444): at android.app.ActivityThread.-wrap1(Unknown Source:0)
07-14 20:30:42.585 E/Xposed ( 5444): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
07-14 20:30:42.585 E/Xposed ( 5444): at android.os.Handler.dispatchMessage(Handler.java:105)
07-14 20:30:42.585 E/Xposed ( 5444): at android.os.Looper.loop(Looper.java:164)
07-14 20:30:42.585 E/Xposed ( 5444): at android.app.ActivityThread.main(ActivityThread.java:6798)
07-14 20:30:42.585 E/Xposed ( 5444): at java.lang.reflect.Method.invoke(Native Method)
07-14 20:30:42.585 E/Xposed ( 5444): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-14 20:30:42.585 E/Xposed ( 5444): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-14 20:30:42.585 E/Xposed ( 5444): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
07-14 20:30:42.591 I/Xposed ( 5444): Removed hooks: KeyboardHooks LayoutChange, Dependency invalidated
07-14 20:30:42.591 I/Xposed ( 5444): Removed hooks: KeyboardHooks InvalidateLayout, Dependency invalidated
07-14 20:30:42.591 I/Xposed ( 5444): Removed hooks: PopupHooks Modify, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: KeyHooks Definition, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: KeyHooks Cancel, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: SelectionHooks, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: EmojiHooks Base, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: PredictionHooks, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: PredictionHooks More, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: PredictionHooks Priority, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: KeyboardHooks PunctuationSpace, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: KeyboardHooks Theme, Dependency invalidated
07-14 20:30:42.592 I/Xposed ( 5444): Removed hooks: SoundHooks base, Dependency invalidated
07-14 20:30:42.601 I/Xposed ( 5444): Removed hooks: KeyboardHooks fullscreenMode, Dependency invalidated
07-14 20:30:42.601 I/Xposed ( 5444): Removed hooks: KeyboardHooks keyHeight, Dependency invalidated
07-14 20:30:42.601 I/Xposed ( 5444): Removed hooks: Hardkey SHortcuts base, Dependency invalidated
07-14 20:30:42.618 I/Xposed ( 5444): Exi/LoadPackageHook, Finished hooking work incom.touchtype.swiftkey

**Comment by achozex** [comment]
version 7.0.8.365

**Comment by Nordskog** [comment]
You are most likely using an old version of the module, as this issue was introduced by a Swiftkey update about a month back, and fixed in version 1.5.3 of this module soon after.
The Xposed Installer is /supposed/ to update its list of modules once a day, but that doesn't seem to happen properly. 

The currently version of the module of 1.5.3, and can be downloaded directly from the Xposed Repository using a browser: [http://repo.xposed.info/module/com.mayulive.swiftkeyexi](http://repo.xposed.info/module/com.mayulive.swiftkeyexi)

If I am mistaken and you are  in fact using the latest version of the module, let me know.

**Comment by achozex** [comment]
installed it from web , it works now , thank you!


Strangely the version shown in the xposed installed is 1.4.3
