### ISSUE TITLE
Cannot rename custom emoji-tab. 

### ISSUE THREAD

**Issue by dinosw** [Nordskog/SwiftKeyExi#44]
I am unable to rename my custom Emoji-tabs. 
I have tried using only symbols, only text, and a mix of both. But the new name is not saved when I click the pen-icon.

**Comment by Nordskog** [comment]
The pen icon lets you enter pick mode, letting you select an emoji from any panel as the name of the panel. 
Hitting "done" saves the change.

Example: https://streamable.com/jzlkd

**Comment by Nordskog** [comment]
I'm going to assume this resolves the issue.
Please reopen it if you are still having problems.
