### ISSUE TITLE
Feature: ability to autochange keyboard theme in each application

### ISSUE THREAD

**Issue by poddex** [Nordskog/SwiftKeyExi#53]
Hello.
Can you make a theme engine for swiftkey?
To make an ability to associate different themes with each application that I want.
For example, If I want to use some purple theme with Viber, I associate the Viber app with purple theme in Exi Settings. Each theme for each app, when app launched, Swiftkey theme changes on the fly.
Is it possible?
Thanks.

**Comment by Nordskog** [comment]
Without looking at the actual code for changing themes, I imagine it would be pretty straight forward to do. 

I'm probably not going to do it anytime soon, but may look into it the next time the Swiftkey team break something and I have to make other changes.

**Comment by Nordskog** [comment]
Implemented as an intent in https://github.com/Nordskog/SwiftKeyExi/commit/174f8499d33fac7063e8c36438a34c515ad5ec4d

Detailed instructions on usage can be found in the 2.0.3 XDA release post: https://forum.xda-developers.com/showpost.php?p=78892109&postcount=796

**Comment by poddex** [comment]
Re: [Nordskog/SwiftKeyExi] Feature: ability to autochange keyboard theme in each application (#53)



Great thanks! Can you send me your tasker example of "setting theme in Firefox and Chrome" like in XDAthread?
Thanks a lot!
--------------------------------------------------------------
Предыдущее сообщение от reply@reply.github.com, присланное 13 февраля 2019 г., 1:34:07:





Implemented as an intent in 174f849
Detailed instructions on usage can be found in the 2.0.3 XDA release post: https://forum.xda-developers.com/showpost.php?p=78892109&postcount=796

**Comment by poddex** [comment]
Re: [Nordskog/SwiftKeyExi] Feature: ability to autochange keyboard theme in each application (#53)



Already got it. Thanks.
You are the greatest.
I send tons of letters to Swiftkey developers asking them for this theme feature.
Thank you!!!!
--------------------------------------------------------------
Предыдущее сообщение от reply@reply.github.com, присланное 13 февраля 2019 г., 1:34:07:





Implemented as an intent in 174f849
Detailed instructions on usage can be found in the 2.0.3 XDA release post: https://forum.xda-developers.com/showpost.php?p=78892109&postcount=796
