### ISSUE TITLE
Feature: remove auto-inserting spaces after inputting or predicting in Swiftkey.

### ISSUE THREAD

**Issue by poddex** [Nordskog/SwiftKeyExi#64]
Please, please, please!!!
I believe, you can stop this!
Please, add the option to disable auto-spaces after predicted words or after punctuation marks or other word inputting. It's annoying, and Swiftkey devteam ignored this feture request for YEARS.
I believe, you can add this option for easy. I find option "Disable spaces after punctuations" but can't find option to disable auto-spaces after prediction. Please, turn off ALL auto-spaces. Many people says you "great thanks" if you make that.

**Comment by Nordskog** [comment]
Implemented in https://github.com/Nordskog/SwiftKeyExi/commit/267c12b322e2290670e32b1bc64abf9b57861550

See [2.2.2 release post](https://forum.xda-developers.com/showpost.php?p=79601355&postcount=933) for details

**Comment by poddex** [comment]
OOOO, thanks!!!!!!!!!
