### ISSUE TITLE
Feature: Toggles in quick menu actions

### ISSUE THREAD

**Issue by XspeedPL** [Nordskog/SwiftKeyExi#74]
I would love to get incognito mode and auto-correct toggle shortcuts (both at once?), so I can seamlessly switch to typing stuff that aren't real sentences back and forth.

**Comment by Nordskog** [comment]
That would be fairly straight forward to do, and these two are definitely ones that would be nice to be able to toggle quickly.

No promises, but I'll keep it in mind.

**Comment by Nordskog** [comment]
Added with commit https://github.com/Nordskog/SwiftKeyExi/commit/19b09ae865694d2992c8ca4a76e15c17b630bfc0, included in release version 2.5.1.

See the [2.5.1 release post](https://forum.xda-developers.com/showpost.php?p=80940737&postcount=1136) for more info.
