### ISSUE TITLE
Feature Request: "Linebreak" action (Hotkey)

### ISSUE THREAD

**Issue by MrSourceUnknown** [Nordskog/SwiftKeyExi#78]
More and more Android messaging apps are forcing "Enter = Send" with no option to change it, and Swiftkey doesn't let you change that setting manually either.

That's why I think I think it would be great if Exi had the option to set a Linebreak action (like Copy/Paste/Undo, etc.) so we can force linebreaks when typing in such applications.

If added similar to other hotkeys this would make linebreaks accessible from Space Up-Swipe Mode and/or Hotkey shortcut, which I think would be very easy for users to get used to.
I'd even suggest enabling it by default from the L-key (modifier+L) because this is both close to the Enter key, L for Linebreak makes logical sense, and it doesn't intefere with other default actions either.

Added to issue log, as promised on the XDA thread.

**Comment by MrSourceUnknown** [comment]
2.6.0 comment:

Insert Newline hotkey action available and working great! Binding it to Hotkey+L for easy access.

T
H
A
N
K
S
!

**Comment by Nordskog** [comment]
Added in https://github.com/Nordskog/SwiftKeyExi/commit/0db4ff238c3881c4b009354dab39d3b406108623

ヾ(❀╹◡╹)ﾉﾞ❀
XDA was having some issues earlier, and I prefer to close these issues with a link to the release post, so things got a bit delayed.

See the [2.6.0 release post](https://forum.xda-developers.com/showpost.php?p=81915643&postcount=1236) for more details.
