### ISSUE TITLE
Version 2.7.1. Hotkey to ctrl select all, copy and paste is not working 

### ISSUE THREAD

**Issue by usamaiqbal1177** [Nordskog/SwiftKeyExi#90]
Hi.

With your new 2.7.1, the swipes are working fluidly now, but hotkey to copy, paste, select all is not working for some reason. Can u plz have a look. If I'm sending wrong logs, plz tell. 
[EdXposed_Verbose_20200921_151638.txt](https://github.com/Nordskog/SwiftKeyExi/files/5254730/EdXposed_Verbose_20200921_151638.txt)

**Comment by Nordskog** [comment]
Unfortunately this project is not maintained, and is no longer compatible with the latest version of Swiftkey and Swiftkey Beta.

The latest release should be compatible with Swiftkey and Swiftkey Beta versions 7.5.7.4 through 7.6.7.4, maybe a few versions before and after too.

2.7.1 fixes a simple issue with the module itself, but does not fix compatibility with newer versions of Swiftkey.
