### ISSUE TITLE
Adding a feature to make your own keyboard layout.

### ISSUE THREAD

**Issue by IlyasTarpan** [Nordskog/SwiftKeyExi#91]
Proposal for the introduction of a new, very important feature.

Hello Microsoft team. I am grateful to you for making such a good keyboard that works well and pleasantly, and also supports so many languages.

However, this is clearly not enough - it seems to me absolutely necessary that there be a function for creating your own layout. Because, for example, I want to print in the Crimean Tatar language, using the Arabic alphabet (it was used until the 1940s). And there is not a single keyboard layout that would suit me (I need the letters ڭ and ە which are not in either the Persian or Arabic layout.) To type on the phone, I must have 3 layouts installed - Persian for the main input, Arabic for the Eastern Arabic numerals (١٢٣٤٥٦٧٨٩٠), Uyghur for the letters ڭ and ە, and sometimes the Urdu keyboard for the sign ؁. As you can imagine, this is very inconvenient: on a Windows computer, I solved the problem by creating my own layout in the Microsoft Keyboard Layout Creator program, which is very convenient.

And I want a similar feature to be designed in SwiftKey. To be able to easily and quickly create your own layout. So that you can:
1) choose what will be in upper case;
2) what will be in lower case;
3) choose which numbers will be used by default;
4) easily share this keyboard layout with other users so they can install it in SwiftKey and use it;
5) enter words into the keyboard database that can be typed by Swype input, and these words are tied to this layout;
6) Easily share and download dictionaries that are associated with this keyboard layout with other people so that they can set this word list so that keyboards can predict input;
7) add this layout to the list of other layouts, or to the list of "own layouts" (to be able to remove it from quick access, and then add it again);
8) name this layout for convenience.

I hope for your answer.

Sincerely, Ilyas Tarpan.

**Comment by Nordskog** [comment]
Hello!

I'm afraid this is not the repository for Microsoft's Swiftkey, but for a now-defunct Xposed module that modded the Android version of Swiftkey. 
I stopped maintaining it a long time ago, even the old versions require a rooted android phone to function.

Your best for getting the Swiftkey team's attention would probably be their twitter: https://twitter.com/swiftkey
Their support page does have a contact form with a feature request option, but I kinda doubt any of its maintained: https://support.swiftkey.com/hc/en-us/requests/new
